name: image_network
description: Image Network is a package that allows you to render images on the web using CanvasKit without having problems with CORS
version: 1.0.0
homepage: https://github.com/gabrielpatricksouza/image_network

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  webview_flutter_web:
  webview_flutter: ">= 3.0.0 < 4.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

